cmake_minimum_required(VERSION 3.10)
project(arm)
set(CMAKE_CXX_STANDARD 17)
list(APPEND CMAKE_PREFIX_PATH /home/jupyter/local)
find_package(unitree_sdk2 REQUIRED)
add_executable(arm arm.cpp)
target_link_libraries(arm unitree_sdk2)
add_executable(hand_test hand_test.cpp)
target_link_libraries(hand_test unitree_sdk2)