agent:
  seed: 123
  num_steps_per_env: 24
  experiment_name: g1_multiclip 
  logger: wandb
  run_name: multiclip_smoke
  upload_model: false
  max_iterations: 5000
  save_interval: 5000
  run_name: multiclip_smoke

  actor:
    hidden_dims: [1024, 512, 256]
    activation: "elu"
    obs_normalization: true

  critic:
    hidden_dims: [1024, 512, 256]
    activation: "elu"
    obs_normalization: true

  algorithm:
    num_learning_epochs: 5
    num_mini_batches: 4
    learning_rate: 0.0003
    schedule: "adaptive"
    gamma: 0.995
    lam: 0.95
    entropy_coef: 0.001
    desired_kl: 0.01
    max_grad_norm: 1.0
    value_loss_coef: 1.0
    use_clipped_value_loss: true
    clip_param: 0.2
env:
  scene:
    num_envs: 4096
  commands:
    motion:
      split_file: /opt/nb/johan/data/motion_file/phuma_track_v2.split.json
      split: train